all : defender

defender :
	@echo 'Compiling...'
	@g++ -Wall -pthread -o defender ./*.cpp
	@echo ''
	@echo '------------------------------------------------------------------'
	@echo 'Compile done, thank you for using IRC Defender.'
	@echo 'Checkout our opensource project page:'
	@echo 'http://code.google.com/p/unrealircd-ircdefender/'
	@echo ''
	@echo 'Free to help!'
	@echo '------------------------------------------------------------------'
	@echo 'Please edit now defender.conf and than run: ./defender'

clean :
	@echo 'Cleaning...'
	@rm *.o
	@echo 'Cleaning done...'
